### ISSUE TITLE
Loop not working with observable fetched data

### ISSUE THREAD

**Issue by ruslanguns** [JayChase/angular2-useful-swiper#66]
Loop seems to not work when data is loaded from fetch data and provided with Observable or Promise.

I have reference the line with the issue:
> https://github.com/ruslanguns/angular-swiperjs-technique/blob/6cf9e6f69557a317a0eb1510824ae5bb8742c8be/src/app/app.component.ts#L35

Please feel free to reproduce this error and playground with my project in Stackblitz:
>https://stackblitz.com/edit/angular-swiperjs

**Comment by fabiangarga** [comment]
Hello there, async data might affect this since most of the rendering happens without the data being initialized. A very simple fix for this, is to add an `*ngIf` condition to the `swiper` component, that will trigger the rendering only when the data is available. Also you can add the conditional to the `[initialize]` input, if your conditional ever changes.

Hope it helps.

**Comment by ruslanguns** [comment]
yeah! that worked properly! Thank you @fabiangarga !
